const fs = require('fs');
const filepath = 'src/types/index.js';
let content = fs.readFileSync(filepath, 'utf8');

const missingItems = [
  {
    id: 'p45',
    slug: 'boss-bunny',
    name: 'Boss Bunny // Executive Order',
    description: 'La personificación del liderazgo en el inframundo digital.',
    price: 185,
    imageUrl: '/images/products/boss-bunny/color/boss-bunny.png',
    imageUrlColor: '/images/products/boss-bunny/color/boss-bunny.png',
    imageUrlPBN: '/images/products/boss-bunny/paint-by-numbers/boss-bunny.png',
    category: 'Finanzas',
    tags: ['BUNNY', 'BOSS', 'POWER'],
    rarity: 'Epic',
    nodeId: 'NF-BNY-EXE',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Dark',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p46',
    slug: 'hong-kong-mcduck',
    name: 'McDuck // Hong Kong Finance',
    description: 'Prosperidad neón en el distrito financiero.',
    price: 185,
    imageUrl: '/images/products/hong-kong-mcduck/color/hong-kong-mcduck.png',
    imageUrlColor: '/images/products/hong-kong-mcduck/color/hong-kong-mcduck.png',
    category: 'Finanzas',
    tags: ['MCDUCK', 'NEON', 'HK'],
    rarity: 'Legendary',
    nodeId: 'NF-HK-DUCK',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Horizontal',
    theme: 'Cyber',
    variants: ['color'],
  },
  {
    id: 'p47',
    slug: 'mona-lisa',
    name: 'Chaos Mona Lisa // Disruptive Theory',
    description: 'Iconografía clásica fragmentada.',
    price: 185,
    imageUrl: '/images/products/mona-lisa/color/chaos-mona-lisa.png',
    imageUrlColor: '/images/products/mona-lisa/color/chaos-mona-lisa.png',
    category: 'Arte Figurativo',
    tags: ['DA VINCI', 'CHAOS', 'ART'],
    rarity: 'Zenith',
    nodeId: 'NF-ML-CHAOS',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Organic',
    variants: ['color'],
  },
  {
    id: 'p48',
    slug: 'alice-wonderland-street',
    name: 'Alice // Wonderland Street Mural',
    description: 'Esencia rebelde en graffiti de alta fidelidad.',
    price: 185,
    imageUrl: '/images/products/alice-wonderland-street/color/alice_wonderland_street_high_res.png',
    imageUrlColor: '/images/products/alice-wonderland-street/color/alice_wonderland_street_high_res.png',
    imageUrlPBN: '/images/products/alice-wonderland-street/paint-by-numbers/alice_wonderland_street_pbn.png',
    category: 'Alice Protocol',
    tags: ['ALICE', 'STREET', 'WONDERLAND'],
    rarity: 'Legendary',
    nodeId: 'NF-ALC-STR',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Urban',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p49',
    slug: 'wonderland-alice',
    name: 'Wonderland Alice Protocol',
    description: 'Reinterpretación técnica del viaje a través del espejo.',
    price: 185,
    imageUrl: '/images/products/wonderland-alice/color/wonderland-alice.png',
    imageUrlColor: '/images/products/wonderland-alice/color/wonderland-alice.png',
    imageUrlPBN: '/images/products/wonderland-alice/paint-by-numbers/wonderland-alice.png',
    category: 'Alice Protocol',
    tags: ['ALICE', 'CLASSIC', 'WONDERLAND'],
    rarity: 'Epic',
    nodeId: 'NF-ALC-CLS',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p50',
    slug: 'wonderland-mcduck',
    name: 'McDuck // Wonderland PBN',
    description: 'Avaricia y locura en protocolo de trazado.',
    price: 185,
    imageUrl: '/images/products/wonderland-mcduck/paint-by-numbers/wonderland-mcduck.png',
    imageUrlColor: null,
    imageUrlPBN: '/images/products/wonderland-mcduck/paint-by-numbers/wonderland-mcduck.png',
    category: 'Finanzas',
    tags: ['MCDUCK', 'WONDERLAND', 'PBN'],
    rarity: 'Common',
    nodeId: 'NF-WND-DUCK',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Organic',
    variants: ['pbn'],
  }
];

const missingStr = JSON.stringify(missingItems, null, 2).replace(/^\[/, '').replace(/\]$/, ',');
content = content.replace(/(export const SAMPLE_PRODUCTS = \[)/, `$1\n${missingStr}`);

fs.writeFileSync(filepath, content, 'utf8');
console.log("Restored remaining singular pieces.");
