/**
 * NovaFrame Product & Cart Schemas
 * ════════════════════════════════════
 */

export const CATEGORIES = ['Matías Pug', 'Pokémon GB', 'Alice Protocol', 'Mario Steampunk', 'Cultura Geek', 'Finanzas', 'Arte Figurativo'];

export const PRODUCT_VARIANTS = {
  COLOR: {
    id: 'color',
    name: 'Standard Color',
    description: 'Alta fidelidad cromática. Acabado vibrante sobre canvas premium.',
    priceOffset: 0,
  },
  PAINT_BY_NUMBERS: {
    id: 'paint-by-numbers',
    name: 'Paint By Numbers',
    description: 'Protocolo de trazado numérico. Convierte la pieza en tu propio lienzo.',
    priceOffset: -20,
  }
};

export const SIZE_PRICES = {
  '36x46cm': 130,
  '40x50cm': 155,
  '38x78cm': 200,
  '60x80cm': 300,
  '70x100cm': 430,
  '100x150cm': 880,
  '150x200cm': 1680,
};

export const FINISH_PRICES = {
  'Canvas Premium': 65,
  'Lona HD': 35,
  'Digital': -50,
  'Canva Estándar': 0,
  'Canva Acústico (Absorbente)': 145,
  'Aluminio Dibond (Metálico)': 115,
};

export const SAMPLE_PRODUCTS = [

  {
    "id": "p45",
    "slug": "boss-bunny",
    "name": "Boss Bunny // Executive Order",
    "description": "La personificación del liderazgo en el inframundo digital.",
    "price": 185,
    "imageUrl": "/images/products/boss-bunny/color/boss-bunny.webp",
    "imageUrlColor": "/images/products/boss-bunny/color/boss-bunny.webp",
    "imageUrlPBN": "/images/products/boss-bunny/paint-by-numbers/boss-bunny.webp",
    "category": "Finanzas",
    "tags": [
      "BUNNY",
      "BOSS",
      "POWER"
    ],
    "rarity": "Epic",
    "nodeId": "NF-BNY-EXE",
    "featured": false,
    "isBestSeller": false,
    "salesCount": 0,
    "shape": "Vertical",
    "theme": "Dark",
    "variants": [
      "color",
      "pbn"
    ]
  },
  {
    "id": "p46",
    "slug": "hong-kong-mcduck",
    "name": "McDuck // Hong Kong Finance",
    "description": "Prosperidad neón en el distrito financiero.",
    "price": 185,
    "imageUrl": "/images/products/hong-kong-mcduck/color/hong-kong-mcduck.webp",
    "imageUrlColor": "/images/products/hong-kong-mcduck/color/hong-kong-mcduck.webp",
    "category": "Finanzas",
    "tags": [
      "MCDUCK",
      "NEON",
      "HK"
    ],
    "rarity": "Legendary",
    "nodeId": "NF-HK-DUCK",
    "featured": false,
    "isBestSeller": false,
    "salesCount": 0,
    "shape": "Horizontal",
    "theme": "Cyber",
    "variants": [
      "color"
    ]
  },
  {
    "id": "p47",
    "slug": "mona-lisa",
    "name": "Chaos Mona Lisa // Disruptive Theory",
    "description": "Iconografía clásica fragmentada.",
    "price": 185,
    "imageUrl": "/images/products/mona-lisa/color/chaos-mona-lisa.webp",
    "imageUrlColor": "/images/products/mona-lisa/color/chaos-mona-lisa.webp",
    "category": "Arte Figurativo",
    "tags": [
      "DA VINCI",
      "CHAOS",
      "ART"
    ],
    "rarity": "Zenith",
    "nodeId": "NF-ML-CHAOS",
    "featured": false,
    "isBestSeller": false,
    "salesCount": 0,
    "shape": "Vertical",
    "theme": "Organic",
    "variants": [
      "color"
    ]
  },
  {
    "id": "p48",
    "slug": "alice-wonderland-street",
    "name": "Alice // Wonderland Street Mural",
    "description": "Esencia rebelde en graffiti de alta fidelidad.",
    "price": 185,
    "imageUrl": "/images/products/alice-wonderland-street/color/alice_wonderland_street_high_res.webp",
    "imageUrlColor": "/images/products/alice-wonderland-street/color/alice_wonderland_street_high_res.webp",
    "imageUrlPBN": "/images/products/alice-wonderland-street/paint-by-numbers/alice_wonderland_street_pbn.webp",
    "category": "Alice Protocol",
    "tags": [
      "ALICE",
      "STREET",
      "WONDERLAND"
    ],
    "rarity": "Legendary",
    "nodeId": "NF-ALC-STR",
    "featured": false,
    "isBestSeller": false,
    "salesCount": 0,
    "shape": "Vertical",
    "theme": "Urban",
    "variants": [
      "color",
      "pbn"
    ]
  },
  {
    "id": "p49",
    "slug": "wonderland-alice",
    "name": "Wonderland Alice Protocol",
    "description": "Reinterpretación técnica del viaje a través del espejo.",
    "price": 185,
    "imageUrl": "/images/products/wonderland-alice/color/wonderland-alice.webp",
    "imageUrlColor": "/images/products/wonderland-alice/color/wonderland-alice.webp",
    "imageUrlPBN": "/images/products/wonderland-alice/paint-by-numbers/wonderland-alice.webp",
    "category": "Alice Protocol",
    "tags": [
      "ALICE",
      "CLASSIC",
      "WONDERLAND"
    ],
    "rarity": "Epic",
    "nodeId": "NF-ALC-CLS",
    "featured": false,
    "isBestSeller": false,
    "salesCount": 0,
    "shape": "Vertical",
    "theme": "Cyber",
    "variants": [
      "color",
      "pbn"
    ]
  },
  {
    "id": "p50",
    "slug": "wonderland-mcduck",
    "name": "McDuck // Wonderland PBN",
    "description": "Avaricia y locura en protocolo de trazado.",
    "price": 185,
    "imageUrl": "/images/products/wonderland-mcduck/paint-by-numbers/wonderland-mcduck.webp",
    "imageUrlColor": null,
    "imageUrlPBN": "/images/products/wonderland-mcduck/paint-by-numbers/wonderland-mcduck.webp",
    "category": "Finanzas",
    "tags": [
      "MCDUCK",
      "WONDERLAND",
      "PBN"
    ],
    "rarity": "Common",
    "nodeId": "NF-WND-DUCK",
    "featured": false,
    "isBestSeller": false,
    "salesCount": 0,
    "shape": "Vertical",
    "theme": "Organic",
    "variants": [
      "pbn"
    ]
  }
,
  // ── COLECCIONES CONSOLIDADAS ──
  {
    id: 'p-yoshi-ruby',
    slug: 'yoshi-ruby',
    name: 'Yoshi // Ruby Cosmic Series',
    description: 'La esencia de la aventura transformada en gemas cósmicas. Esta serie técnica ofrece variaciones de alta fidelidad desde protocolos cósmicos hasta estados dorados industriales.',
    price: 185,
    imageUrl: '/images/products/yoshi-ruby/color/yoshi-ruby-cosmic.webp',
    imageUrlColor: '/images/products/yoshi-ruby/color/yoshi-ruby-cosmic.webp',
    imageUrlColor2: '/images/products/yoshi-ruby/color/yoshi-variant-v2.webp',
    imageUrlPBN: '/images/products/yoshi-ruby/paint-by-numbers/yoshi-ruby-cosmic.webp',
    imageUrlPBN2: '/images/products/yoshi-ruby/paint-by-numbers/yoshi-sketch-matrix.webp',
    category: 'Mario Steampunk',
    tags: ['YOSHI', 'NINTENDO', 'COSMIC', 'SERIES'],
    rarity: 'Zenith',
    nodeId: 'NF-YSH-COL',
    featured: true,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-pokemon-gb',
    slug: 'pokemon-gb',
    name: 'Pokémon GB // World Explorer Series',
    description: 'Una trilogía de alta resolución que captura los ecosistemas clásicos de Kanto en estética 8-bit. Incluye las expediciones Desert Ruins, Jungle Sanctuary y Forest Cave.',
    price: 185,
    imageUrl: '/images/products/pokemon-gb/color/pokemon-gb-desert.webp',
    imageUrlColor: '/images/products/pokemon-gb/color/pokemon-gb-desert.webp',
    imageUrlColor2: '/images/products/pokemon-gb/color/pokemon-gb-jungle.webp',
    imageUrlColor3: '/images/products/pokemon-gb/color/pokemon-gb-forest.webp',
    imageUrlPBN: '/images/products/pokemon-gb/paint-by-numbers/pokemon-gb-desert.webp',
    imageUrlPBN2: '/images/products/pokemon-gb/paint-by-numbers/pokemon-gb-jungle.webp',
    category: 'Pokémon GB',
    tags: ['POKEMON', 'RETRO', 'SERIES', 'EXPEDITION'],
    rarity: 'Zenith',
    nodeId: 'NF-PKM-COL',
    featured: true,
    isBestSeller: true,
    salesCount: 1540,
    shape: 'Vertical',
    theme: 'Lustre',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-capital-king',
    slug: 'capital-king',
    name: 'Capital Is King // Executive Protocols',
    description: 'La trilogía definitiva sobre el poder financiero. Desde el Oro Imperial hasta la Obsidiana Profunda, capturando la esencia de la autoridad económica.',
    price: 185,
    imageUrl: '/images/products/capital-king/color/capital-is-king-v1.webp',
    imageUrlColor: '/images/products/capital-king/color/capital-is-king-v1.webp',
    imageUrlColor2: '/images/products/capital-king/color/capital-is-king-v2.webp',
    imageUrlColor3: '/images/products/capital-king/color/capital-is-king-v3.webp',
    imageUrlPBN: '/images/products/capital-king/paint-by-numbers/capital-is-king-v1.webp',
    imageUrlPBN2: '/images/products/capital-king/paint-by-numbers/capital-is-king-v2.webp',
    imageUrlPBN3: '/images/products/capital-king/paint-by-numbers/capital-is-king-v3.webp',
    category: 'Finanzas',
    tags: ['CAPITAL', 'POWER', 'SERIES'],
    rarity: 'Zenith',
    nodeId: 'NF-CAP-COL',
    featured: true,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Dark',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-alice-geometric',
    slug: 'alice-geometric',
    name: 'Alice // Geometric Polygon Protocol',
    description: 'Una megacolección de 9 piezas que explora la fragmentación poligonal del País de las Maravillas. Un estudio profundo sobre la lógica botánica y la geometría sagrada.',
    price: 185,
    imageUrl: '/images/products/alice-geometric/color/alice-geometric-v1.webp',
    imageUrlColor: '/images/products/alice-geometric/color/alice-geometric-v1.webp',
    imageUrlColor2: '/images/products/alice-geometric/color/alice-geometric-v2.webp',
    imageUrlColor3: '/images/products/alice-geometric/color/alice-geometric-v3.webp',
    imageUrlColor4: '/images/products/alice-geometric/color/alice-geometric-v4.webp',
    imageUrlColor5: '/images/products/alice-geometric/color/alice-geometric-v5.webp',
    imageUrlColor6: '/images/products/alice-geometric/color/alice-geometric-v6.webp',
    imageUrlColor7: '/images/products/alice-geometric/color/alice-geometric-v7.webp',
    imageUrlColor8: '/images/products/alice-geometric/color/alice-geometric-v8.webp',
    imageUrlColor9: '/images/products/alice-geometric/color/alice-geometric-v9.webp',
    category: 'Alice Protocol',
    tags: ['ALICE', 'POLYGON', 'GEOMETRIC', 'SERIES'],
    rarity: 'Zenith',
    nodeId: 'NF-ALC-GEO-COL',
    featured: true,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Cuadrado',
    theme: 'Cyber',
    variants: ['color'],
  },
  {
    id: 'p-matias-bath',
    slug: 'matias-bubble-bath',
    name: 'Matías // The Bubble Bath Collection',
    description: 'Una serie técnica que captura la evolución del protocolo de higiene de Matías. Incluye los estados Alpha, Beta y Gamma de inmersión en espuma mutada.',
    price: 185,
    imageUrl: '/images/products/matias-bubble-bath/color/matias-bubble-bath-v1.webp',
    imageUrlColor: '/images/products/matias-bubble-bath/color/matias-bubble-bath-v1.webp',
    imageUrlColor2: '/images/products/matias-bubble-bath/color/matias-bubble-bath-v2.webp',
    imageUrlColor3: '/images/products/matias-bubble-bath/color/matias-bubble-bath-v3.webp',
    category: 'Matías Pug',
    tags: ['MATIAS', 'PUG', 'DOG', 'BATH', 'ZENITH'],
    rarity: 'Zenith',
    nodeId: 'NF-MAT-COL',
    featured: true,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Lustre',
    variants: ['color'],
  },
  {
    id: 'p38',
    slug: 'courage-berserk',
    name: 'Courage // The Black Swordsman Series',
    description: 'Quinteto de piezas de alta fidelidad que documentan la lucha interna y externa del guerrero. De la oscuridad absoluta a la iluminación industrial.',
    price: 185,
    imageUrl: '/images/products/courage-berserk/color/courage-berserk-v1.webp',
    imageUrlColor: '/images/products/courage-berserk/color/courage-berserk-v1.webp',
    imageUrlColor2: '/images/products/courage-berserk/color/courage-berserk-v2.webp',
    imageUrlColor3: '/images/products/courage-berserk/color/courage-berserk-v3.webp',
    imageUrlColor4: '/images/products/courage-berserk/color/courage-berserk-v4.webp',
    imageUrlColor5: '/images/products/courage-berserk/color/courage-berserk-v5.webp',
    category: 'Cultura Geek',
    tags: ['BERSERK', 'COURAGE', 'ANIME', 'SERIES'],
    rarity: 'Legendary',
    nodeId: 'NF-CRG-COL',
    featured: true,
    isBestSeller: true,
    salesCount: 342,
    shape: 'Vertical',
    theme: 'Dark',
    variants: ['color'],
  },
  // ── OTRAS PIEZAS SINGULARES ──
  {
    id: 'p1',
    slug: 'bunny-ambition-wealth',
    name: 'Ambition // Money Bunny',
    description: 'Símbolo de la ambición y el poder en el nuevo orden digital.',
    price: 185,
    imageUrl: '/images/products/bunny-ambition/color/bunny_ambition_wealth_high_res.webp',
    imageUrlColor: '/images/products/bunny-ambition/color/bunny_ambition_wealth_high_res.webp',
    imageUrlPBN: '/images/products/bunny-ambition/paint-by-numbers/bunny_ambition_wealth_pbn.webp',
    category: 'Finanzas',
    tags: ['MONEY', 'BUNNY', 'ZENITH'],
    rarity: 'Zenith',
    nodeId: 'NF-BNY-777',
    featured: true,
    isBestSeller: true,
    salesCount: 2840,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p13',
    slug: 'mona-lisa',
    name: 'Savage Mona Lisa',
    description: 'Iconografía clásica bajo el prisma de la disrupción industrial.',
    price: 185,
    imageUrl: '/images/products/mona-lisa/color/savage-mona-lisa.webp',
    imageUrlColor: '/images/products/mona-lisa/color/savage-mona-lisa.webp',
    category: 'Arte Figurativo',
    tags: ['MONA LISA', 'SAVAGE', 'ART'],
    rarity: 'Epic',
    nodeId: 'NF-ML-01',
    featured: true,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Organic',
    variants: ['color'],
  },
  {
    id: 'p19',
    slug: 'pikachu-steampunk',
    name: 'Pikachu // Steampunk Mutation',
    description: 'Eléctrico, industrial y mecánico. La evolución final del icono de Kanto.',
    price: 185,
    imageUrl: '/images/products/pikachu-steampunk/color/pikachu-steampunk.webp',
    imageUrlColor: '/images/products/pikachu-steampunk/color/pikachu-steampunk.webp',
    imageUrlPBN: '/images/products/pikachu-steampunk/paint-by-numbers/pikachu-steampunk.webp',
    category: 'Cultura Geek',
    tags: ['PIKACHU', 'STEAMPUNK', 'POKEMON'],
    rarity: 'Legendary',
    nodeId: 'NF-PK-STEAM',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Cuadrado',
    theme: 'Cyber',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p10',
    slug: 'wall-street-mcduck',
    name: 'Scrooge // Wall Street Protocol',
    description: 'Avaricia, poder y el distrito financiero. El alma del capital.',
    price: 185,
    imageUrl: '/images/products/wall-street-mcduck/color/wall-street-mcduck.webp',
    imageUrlColor: '/images/products/wall-street-mcduck/color/wall-street-mcduck.webp',
    category: 'Finanzas',
    tags: ['MCDUCK', 'WALL STREET', 'MONEY'],
    rarity: 'Epic',
    nodeId: 'NF-MCD-WS',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Dark',
    variants: ['color'],
  },
  {
    id: 'p4',
    slug: 'napoleon-rebellion',
    name: 'Napoleon // Empire Rebellion',
    description: 'Liderazgo histórico bajo una estética disruptiva.',
    price: 185,
    imageUrl: '/images/products/napoleon-rebellion/color/napoleon_empire_rebellion_high_res.webp',
    imageUrlColor: '/images/products/napoleon-rebellion/color/napoleon_empire_rebellion_high_res.webp',
    category: 'Arte Figurativo',
    tags: ['NAPOLEON', 'POWER', 'HISTORY'],
    rarity: 'Legendary',
    nodeId: 'NF-NAP-01',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Urban',
    variants: ['color'],
  },
  {
    id: 'p-lego-alice',
    slug: 'lego-alice',
    name: 'Lego Alice // Brick Protocol',
    description: 'Construcción modular de la realidad wonderland.',
    price: 185,
    imageUrl: '/images/products/lego-alice/color/lego-alice-v1.webp',
    imageUrlColor: '/images/products/lego-alice/color/lego-alice-v1.webp',
    imageUrlColor2: '/images/products/lego-alice/color/lego-alice-v2.webp',
    imageUrlColor3: '/images/products/lego-alice/color/lego-alice-v3.webp',
    imageUrlColor4: '/images/products/lego-alice/color/lego-alice-guide.webp',
    category: 'Alice Protocol',
    tags: ['LEGO', 'ALICE', 'BRICK'],
    rarity: 'Zenith',
    nodeId: 'NF-LGO-ALC',
    featured: true,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color'],
  },
  {
    id: 'p-alice-pixel',
    slug: 'alice-pixel',
    name: 'Alice Pixel // Genesis Protocol',
    description: 'El origen digital de la Reina de Corazones.',
    price: 185,
    imageUrl: '/images/products/alice-pixel/color/alice-pixel-cosmic.webp',
    imageUrlColor: '/images/products/alice-pixel/color/alice-pixel-cosmic.webp',
    imageUrlColor2: '/images/products/alice-pixel/color/alice-pixel-night.webp',
    imageUrlColor3: '/images/products/alice-pixel/color/alice-pixel-sunset.webp',
    imageUrlPBN: '/images/products/alice-pixel/paint-by-numbers/alice-pixel-night.webp',
    imageUrlPBN2: '/images/products/alice-pixel/paint-by-numbers/alice-pixel-sunset.webp',
    category: 'Alice Protocol',
    tags: ['PIXEL', 'ALICE', '8-BIT'],
    rarity: 'Legendary',
    nodeId: 'NF-ALC-PXL',
    featured: true,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-cyber-bunny',
    slug: 'cyber-bunny',
    name: 'Cyber Bunny // High Frequency',
    description: 'Protocolo de alta frecuencia en estética leporina.',
    price: 185,
    imageUrl: '/images/products/cyber-bunny/color/cyber_bunny_v1.webp',
    imageUrlColor: '/images/products/cyber-bunny/color/cyber_bunny_v1.webp',
    imageUrlPBN: '/images/products/cyber-bunny/paint-by-numbers/cyber_bunny_pbn.webp',
    category: 'Cultura Geek',
    tags: ['BUNNY', 'CYBER', 'TECH'],
    rarity: 'Epic',
    nodeId: 'NF-CYB-BNY',
    featured: true,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-charmander',
    slug: 'charmander-evolution',
    name: 'Charmander // Cyber Heritage',
    description: 'Evolución ígnea bajo protocolos de red.',
    price: 185,
    imageUrl: '/images/products/charmander-evolution/color/charmander-cyber.webp',
    imageUrlColor: '/images/products/charmander-evolution/color/charmander-cyber.webp',
    imageUrlColor2: '/images/products/charmander-evolution/color/charmander-stained-glass.webp',
    imageUrlPBN: '/images/products/charmander-evolution/paint-by-numbers/charmander-cyber.webp',
    imageUrlPBN2: '/images/products/charmander-evolution/paint-by-numbers/charmander-stained-glass.webp',
    category: 'Pokémon GB',
    tags: ['CHARMANDER', 'POKEMON', 'FIRE'],
    rarity: 'Legendary',
    nodeId: 'NF-PKM-CHR',
    featured: true,
    shape: 'Vertical',
    theme: 'Lustre',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-alice-awakening',
    slug: 'alice-awakening',
    name: 'Alice Awakening // Protocol Start',
    description: 'El despertar de la consciencia en el Jardín de las Rosas.',
    price: 185,
    imageUrl: '/images/products/alice-awakening/color/alice_awakening_protocol.webp',
    imageUrlColor: '/images/products/alice-awakening/color/alice_awakening_protocol.webp',
    category: 'Alice Protocol',
    tags: ['ALICE', 'AWAKENING', 'FLOWER'],
    rarity: 'Zenith',
    nodeId: 'NF-ALC-AWK',
    featured: true,
    shape: 'Vertical',
    theme: 'Organic',
    variants: ['color'],
  },
  {
    id: 'p-alice-dreaming',
    slug: 'alice-dreaming',
    name: 'Alice Dreaming // Data Stream',
    description: 'Protocolo de inmersión en el subconsciente digital.',
    price: 185,
    imageUrl: '/images/products/alice-dreaming/color/alice_dreaming_data.webp',
    imageUrlColor: '/images/products/alice-dreaming/color/alice_dreaming_data.webp',
    category: 'Alice Protocol',
    tags: ['ALICE', 'DREAM', 'DATA'],
    rarity: 'Epic',
    nodeId: 'NF-ALC-DRM',
    featured: true,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color'],
  },
  {
    id: 'p-alice-typography',
    slug: 'alice-typography',
    name: 'Alice // Typographic Studio',
    description: 'La arquitectura del lenguaje en el protocolo Wonderland.',
    price: 185,
    imageUrl: '/images/products/alice-typography/color/alice_typography_urban.webp',
    imageUrlColor: '/images/products/alice-typography/color/alice_typography_urban.webp',
    imageUrlColor2: '/images/products/alice-typography/color/alice_typography_studio.webp',
    imageUrlPBN: '/images/products/alice-typography/paint-by-numbers/alice_typography_pbn.webp',
    category: 'Alice Protocol',
    tags: ['ALICE', 'TYPO', 'URBAN'],
    rarity: 'Legendary',
    nodeId: 'NF-ALC-TYP',
    featured: true,
    shape: 'Vertical',
    theme: 'Urban',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-chrono-rabbit',
    slug: 'chrono-rabbit',
    name: 'Chrono Rabbit // Zenith Flow',
    description: 'El guardián del tiempo en el núcleo NovaFrame.',
    price: 185,
    imageUrl: '/images/products/chrono-rabbit/color/chrono_rabbit_zenith.webp',
    imageUrlColor: '/images/products/chrono-rabbit/color/chrono_rabbit_zenith.webp',
    imageUrlPBN: '/images/products/chrono-rabbit/paint-by-numbers/chrono_rabbit_pbn.webp',
    category: 'Cultura Geek',
    tags: ['RABBIT', 'TIME', 'CHRONO'],
    rarity: 'Zenith',
    nodeId: 'NF-CHR-RB',
    featured: true,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color', 'pbn'],
  },
  {
    id: 'p-white-rabbit-lego',
    slug: 'white-rabbit-lego',
    name: 'White Rabbit // Lego Protocol',
    description: 'Instanciación modular del heraldo de Wonderland.',
    price: 185,
    imageUrl: '/images/products/white-rabbit-lego/color/white-rabbit-lego-v1.webp',
    imageUrlColor: '/images/products/white-rabbit-lego/color/white-rabbit-lego-v1.webp',
    imageUrlColor2: '/images/products/white-rabbit-lego/color/white-rabbit-lego-v2.webp',
    imageUrlColor3: '/images/products/white-rabbit-lego/color/white-rabbit-lego-v3.webp',
    category: 'Alice Protocol',
    tags: ['LEGO', 'RABBIT', 'WHITE'],
    rarity: 'Zenith',
    nodeId: 'NF-WRL-LGO',
    featured: true,
    shape: 'Vertical',
    theme: 'Lustre',
    variants: ['color'],
  },
  {
    id: 'p-mario-steam',
    slug: 'mario-steampunk',
    name: 'Mario // Steampunk Revolution',
    description: 'El fontanero del Reino Champiñón bajo protocolos de ingeniería a vapor.',
    price: 185,
    imageUrl: '/images/products/mario-steampunk/paint-by-numbers/mario-pbn-v1.webp',
    imageUrlPBN: '/images/products/mario-steampunk/paint-by-numbers/mario-pbn-v1.webp',
    imageUrlPBN2: '/images/products/mario-steampunk/paint-by-numbers/mario-pbn-v2.webp',
    imageUrlPBN3: '/images/products/mario-steampunk/paint-by-numbers/mario-pbn-v3.webp',
    category: 'Mario Steampunk',
    tags: ['MARIO', 'STEAMPUNK', 'PBN'],
    rarity: 'Legendary',
    nodeId: 'NF-MAR-STEAM',
    featured: true,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['pbn'],
  },
  {
    id: 'p-multiverse-series',
    slug: 'multiverse-series',
    name: 'The Multiverse Series // Protocol Evolution',
    description: 'Una exploración técnica a través de 8 dimensiones paralelas de una misma obra maestra. Cada variación captura un flujo de datos único y una manifestación de personajes de diferentes realidades.',
    price: 185,
    imageUrl: '/images/products/multiverse-series/color/v1.webp',
    imageUrlColor: '/images/products/multiverse-series/color/v1.webp',
    imageUrlColor2: '/images/products/multiverse-series/color/v2.webp',
    imageUrlColor3: '/images/products/multiverse-series/color/v3.webp',
    imageUrlColor4: '/images/products/multiverse-series/color/v4.webp',
    imageUrlColor5: '/images/products/multiverse-series/color/v5.webp',
    imageUrlColor6: '/images/products/multiverse-series/color/v6.webp',
    imageUrlColor7: '/images/products/multiverse-series/color/v7.webp',
    imageUrlColor8: '/images/products/multiverse-series/color/v8.webp',
    category: 'Cultura Geek',
    tags: ['MULTIVERSE', 'DIMENSION', 'EVOLUTION', 'SERIES'],
    rarity: 'Legendary',
    nodeId: 'NF-MLT-COL',
    featured: false,
    isBestSeller: false,
    salesCount: 0,
    shape: 'Vertical',
    theme: 'Cyber',
    variants: ['color'],
  }
];
